multiplexer_address: 0x70
lcd_address: 0x27
api_url: "http://localhost:8080/api/access-portals/door-status"
controller_id: "585285"

nfc_channels:
  inside: 0
  outside: 1
lcd_channel: 2

# Bu değerler artık controller'lar içinde sabit tanımlandı
# ve kullanılmıyor, fakat geriye dönük uyumluluk için tutuldu
buzzer_pins:
  inside: 23
  outside: 24

led_pins:
  inside: 18
  outside: 12

led_pixel_count: 8 