# I2C ayarları
I2C_BUS = 1
MULTIPLEXER_ADDR = 0x70

# NFC okuyucu kanalları
INSIDE_NFC_CHANNEL = 0
OUTSIDE_NFC_CHANNEL = 1

# GPIO pinleri
INSIDE_LED_PIN = 17
OUTSIDE_LED_PIN = 27
INSIDE_BUZZER_PIN = 22
OUTSIDE_BUZZER_PIN = 23

# Kart okuma ayarları
CARD_READ_TIMEOUT = 0.1  # saniye
RELAY_TRIGGER_TIME = 3   # saniye 